name: Aesir Release Pipeline

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    name: "Build: ${{ matrix.config.name }} / ${{ matrix.config.platform }}"
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: true
      matrix:
        config:
          - {
            name: "Windows Latest",
            os: windows-latest,
            platform: x64
          }
          - {
            name: "Ubuntu Latest",
            os: ubuntu-latest,
            platform: x64
          }
          - {
            name: "macOS-11",
            os: macos-11,
            platform: x64
          }
          - {
            name: "macOS Latest",
            os: macos-latest,
            platform: arm64
          }

    env:
      PLATFORM: ${{ matrix.config.platform }}
      VERSION: ${{ github.ref_name }}  # This extracts the tag name

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18.13.0

      - name: Install dependencies
        run: sudo -H pip install setuptools && npm install --quiet

      - name: Build ${{ matrix.config.name }}
        if: matrix.config.os == 'windows-latest'
        run: npm run build

      - name: Build ${{ matrix.config.name }}
        if: matrix.config.os == 'ubuntu-latest'
        run: npm run build:linux-$PLATFORM

      - name: Build ${{ matrix.config.name }}
        if: matrix.config.name == 'macOS-11'
        run: npm run build:mac-$PLATFORM

      - name: Build ${{ matrix.config.name }}
        if: matrix.config.name == 'macOS Latest'
        run: npm run build:mac-$PLATFORM

      - name: Upload artifact for Windows
        if: matrix.config.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: Aesir-Setup-${{ env.VERSION }}.exe
          path: dist/Aesir-Setup-${{ env.VERSION }}.exe

      - name: Upload artifact for Ubuntu
        if: matrix.config.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: Aesir-${{ env.VERSION }}-amd64.deb
          path: dist/Aesir-${{ env.VERSION }}-amd64.deb

      - name: Upload artifact for macOS Intel
        if: matrix.config.name == 'macOS-11'
        uses: actions/upload-artifact@v3
        with:
          name: Aesir-${{ env.VERSION }}-intel.dmg
          path: dist/Aesir-${{ env.VERSION }}-intel.dmg

      - name: Upload artifact for macOS ARM
        if: matrix.config.name == 'macOS Latest'
        uses: actions/upload-artifact@v3
        with:
          name: Aesir-${{ env.VERSION }}-arm64.dmg
          path: dist/Aesir-${{ env.VERSION }}-arm64.dmg
